### ISSUE TITLE
[Fleet] Invalid token causes agent migration to hang and block new attempts

### ISSUE THREAD

**Issue by rseldner** [elastic/elastic-agent#10909]
**Kibana version:**
9.2.0.

**Elasticsearch version:**
9.2.0

**Original install method (e.g. download page, yum, from source, etc.):**
ESS/ECH

**Describe the bug:**
The agent migration feature sort of breaks if you specify an invalid/revoked token.
It gets stuck on that action.
Subsequent migration attempts do nothing.

No impact if you:
- restart the agent itself
- restart Kibana
- restart fleet
- cancel the migration agent action

However, I can get it working again if I switch the agent to a different policy, restart the agent, and try the migration again.

I reproduced this on two separate clusters where I was testing the feature and migrating the agent back and forth.

This does not seem to occur on all types of failures.  I forced a connectivity problem (disabled routing to the new fleet server) and the migration task failed and completed, as one would expect, and allowed me to successfully retry.

Sidenote:
Sometimes the agent would stop checking into the original fleet and go offline (though ingest continued to work) in which case an agent restart on the host was needed to bring it back online.

**Steps to reproduce:**
1. Install and Enroll elastic agent into fleet
2. Attempt to migrate the agent but specify an known invalid string for the token (any arbitrary text will do)
    - This failed migration will indefinitely remain in an IN_PROGRESS state
3. Attempt to migrate the agent again using a valid token
    - this action will never run and also remain IN_PROGRESS indefinitely
4. Attach the agent to any other agent policy
5. retry the migration (this succeeds)

**Expected behavior:**
Failed agent tasks should not run indefinitely
Subsequent migration attempts should be able to run without any extra shenanigans

**Screenshots (if relevant):**
Sorry for the size of the screenshot.  I had to zoom out a lot to capture the info from the screenshot
<img width="1729" height="978" alt="Image" src="https://github.com/user-attachments/assets/a412b72a-19c2-4f37-a4d7-7d2db8cb7a2c" />

Agent Action cancellation request succeeded...

<img width="950" height="125" alt="Image" src="https://github.com/user-attachments/assets/a9588521-3799-48c2-87a5-5dafef4d00c7" />

but continues `IN_PROGRESS` as do the subsequent corrected attempts

<img width="932" height="685" alt="Image" src="https://github.com/user-attachments/assets/1d5c4a2d-2116-4347-8388-938bfde01bd8" />

**Provide logs and/or server output (if relevant):**
Agent logs indicate the initial bad token migration continues to retry the new enrollment hours later even after retrying with corrected token.

```sh
Oct 28, 2025 @ 10:05:53.395	elastic_agent	(null)	Error detected: fail to execute request to fleet-server: status code: 401, fleet-server returned an error: ErrUnauthorized, message: unauthorized, will retry in a moment.	
Oct 28, 2025 @ 10:05:52.919	elastic_agent	(null)	Retrying enrollment to URL: https://[redacted].fleet.us-central1.gcp.cloud.es.io//	
Oct 28, 2025 @ 09:57:47.717	elastic_agent	(null)	Error detected: fail to execute request to fleet-server: status code: 401, fleet-server returned an error: ErrUnauthorized, message: unauthorized, will retry in a moment.	
Oct 28, 2025 @ 09:57:47.246	elastic_agent	(null)	Retrying enrollment to URL: https://[redacted].fleet.us-central1.gcp.cloud.es.io//	
Oct 28, 2025 @ 09:48:37.934	elastic_agent	(null)	Error detected: fail to execute request to fleet-server: status code: 401, fleet-server returned an error: ErrUnauthorized, message: unauthorized, will retry in a moment.	
Oct 28, 2025 @ 09:48:37.475	elastic_agent	(null)	Retrying enrollment to URL: https://[redacted].fleet.us-central1.gcp.cloud.es.io//	
Oct 28, 2025 @ 09:40:14.098	elastic_agent	(null)	Error detected: fail to execute request to fleet-server: status code: 401, fleet-server returned an error: ErrUnauthorized, message: unauthorized, will retry in a moment.	
Oct 28, 2025 @ 09:40:13.359	elastic_agent	(null)	Retrying enrollment to URL: https://[redacted].fleet.us-central1.gcp.cloud.es.io//	
Oct 28, 2025 @ 09:32:55.673	elastic_agent	(null)	Error detected: fail to execute request to fleet-server: status code: 401, fleet-server returned an error: ErrUnauthorized, message: unauthorized, will retry in a moment.	
Oct 28, 2025 @ 09:32:55.179	elastic_agent	(null)	Retrying enrollment to URL: https://[redacted].fleet.us-central1.gcp.cloud.es.io//	
Oct 28, 2025 @ 09:31:57.318	elastic_agent	(null)	Checkin request to fleet-server succeeded after 1 failures	
Oct 28, 2025 @ 09:20:04.255	elastic_agent	(null)	Possible transient error during checkin with fleet-server, retrying	
Oct 28, 2025 @ 08:44:43.471	elastic_agent	(null)	Error detected: fail to execute request to fleet-server: status code: 401, fleet-server returned an error: ErrUnauthorized, message: unauthorized, will retry in a moment.	
Oct 28, 2025 @ 08:44:42.542	elastic_agent	(null)	Retrying enrollment to URL: https://[redacted].fleet.us-central1.gcp.cloud.es.io//	
Oct 28, 2025 @ 08:37:22.637	elastic_agent	(null)	Error detected: fail to execute request to fleet-server: status code: 401, fleet-server returned an error: ErrUnauthorized, message: unauthorized, will retry in a moment.	
Oct 28, 2025 @ 08:37:22.164	elastic_agent	(null)	Retrying enrollment to URL: https://[redacted].fleet.us-central1.gcp.cloud.es.io//	
Oct 28, 2025 @ 08:31:26.486	elastic_agent	(null)	Error detected: fail to execute request to fleet-server: status code: 401, fleet-server returned an error: ErrUnauthorized, message: unauthorized, will retry in a moment.	
Oct 28, 2025 @ 08:31:26.008	elastic_agent	(null)	Retrying enrollment to URL: https://[redacted].fleet.us-central1.gcp.cloud.es.io//	
Oct 28, 2025 @ 08:27:33.981	elastic_agent	(null)	Error detected: fail to execute request to fleet-server: status code: 401, fleet-server returned an error: ErrUnauthorized, message: unauthorized, will retry in a moment.	
Oct 28, 2025 @ 08:27:33.492	elastic_agent	(null)	Retrying enrollment to URL: https://[redacted].fleet.us-central1.gcp.cloud.es.io//	
Oct 28, 2025 @ 08:25:34.593	elastic_agent	(null)	Error detected: fail to execute request to fleet-server: status code: 401, fleet-server returned an error: ErrUnauthorized, message: unauthorized, will retry in a moment.	
Oct 28, 2025 @ 08:25:34.593	elastic_agent	(null)	1st enrollment attempt failed, retrying enrolling to URL: https://[redacted].fleet.us-central1.gcp.cloud.es.io// with exponential backoff (init 5s, max 10m0s)	
```

**Any additional context:**

**Comment by kpollich** [comment]
cc @michalpristas

**Comment by michalpristas** [comment]
seems like a valid issue, working on it today. proper disaster recovery for this case is missing

**Comment by michalpristas** [comment]
ok it was not about disaster recovery, this is properly implemented, the thing is enrollment is performed indefinitely and as so not acking failure.without failure ack fleet does not update action status and does not allow another migration action to be triggered

**Comment by michalpristas** [comment]
fixed got merged today, ready to re-test with next SNAPSHOT

**Comment by rseldner** [comment]
Thanks! 
I see the fix is elastic-agent focused but this scenario has left me wondering if there's anything that needs to be done from Fleet/Kibana side to be able to clean up these stuck/orphaned tasks.  Even after managing to get all the agents migrated, I still have these in progress tasks that won't go away until they reach the 30d expiration.

---

**Screenshot of in progress tasks (none of these are valid at this point in time)**

<img width="499" height="807" alt="Image" src="https://github.com/user-attachments/assets/3b59c343-f2c8-46fb-8d5a-1cb22266e5dd" />


---

The cancel agent action API is having no effect on these actions.

Two workarounds I've been able to use are:

- update the corresponding `.fleet-actions-7` document with an expiration date in the past.  This completely removes the task from the Agent Actions panel.
```
POST .fleet-actions-7/_update/7972840c-33d7-40d6-ab3f-a7ebc193897f
{
  "doc": {
    "expiration": "2025-10-29T16:31:56.230Z"
  }
}
```
- write a new document into `.fleet-actions-results` for the action+agent. This one seems to work nicely as it moves the task down to completed and displays the error we provided
```
curl -u xxxx:xxxx -X POST "https://xxxxx.es.us-central1.gcp.cloud.es.io/.fleet-actions-results/_doc/20fa8ce0-05fd-4eac-aa43-ca0aee8e2189:2ae0be87-2e0a-4871-bc56-ae0588d60399?op_type=create" -H "Content-Type: application/json" -H "x-elastic-product-origin:fleet" -d '{
    "action_id": "20fa8ce0-05fd-4eac-aa43-ca0aee8e2189",
    "agent_id": "2ae0be87-2e0a-4871-bc56-ae0588d60399",
    "error": "action manually expired",
    "@timestamp": "2025-10-29T16:31:56.230Z"
  }'
```

<img width="547" height="362" alt="Image" src="https://github.com/user-attachments/assets/39d16de7-5e17-4b2c-98df-67247417b37b" />


---

I know neither of these approaches should be generally used, but they illustrate the potential need for some sort of forced cleanup for orphaned agent actions that does not rely on waiting 30d, maybe a `force` flag on the cancel agent action API.

Perhaps that should be its own new issue for an enhancement.

**Comment by michalpristas** [comment]
@jillguyonnet is there something we could do here

**Comment by jillguyonnet** [comment]
@rseldner For confirmation, were all the stuck migrate actions created before the fix, i.e. would actions with an invalid enrollment token now correctly fail?

If so, you're right that actions that were created before the fix will remain in progress until cleaned up by Fleet Server after 30 days. This is certainly not ideal, but in general I don't think there should be a situation where an action is forever stuck in progress, that should be considered a bug.

Cancelling is only supported for upgrade actions, which can be scheduled and/or have a rollout period. I don't think it would make sense for immediate actions, such as agent migration, as we might end up in an unpredictable state.

The workarounds you mentioned will work for cleaning up "orphaned" in-progress actions. A Fleet enhancement we could consider could be to add a duration (e.g. a day) after which the in-progress action is considered stuck, then the UI could offer the user a way to manually fail the action. This could potentially be risky, so there would need to be adequate warnings. I don't think an automated cleanup mechanism in the backend would make sense, a stuck action should probably require user attention.

cc @kpollich @juliaElastic

**Comment by ebeahan** [comment]
@michalpristas with https://github.com/elastic/elastic-agent/pull/10946 merged, is this issue ready to be closed?

**Comment by rseldner** [comment]
this fell off my radar.  Just following up on the last comment...

>were all the stuck migrate actions created before the fix

yes and I understand the fix would not have addressed that.  I was just bringing the not-so-great UX to light. But the likelihood is reduced with the fix.

>Cancelling is only supported for upgrade actions, which can be scheduled and/or have a rollout period...

hmm I see.  that is not clear in the API doc (doesn't say much TBH 😅 ). https://www.elastic.co/docs/api/doc/serverless/operation/operation-post-fleet-agents-actions-actionid-cancel

>The workarounds you mentioned will work for cleaning up "orphaned" in-progress actions. A Fleet enhancement we could consider could be to add a duration (e.g. a day) after which the in-progress action is considered stuck, then the UI could offer the user a way to manually fail the action. This could potentially be risky, so there would need to be adequate warnings. I don't think an automated cleanup mechanism in the backend would make sense, a stuck action should probably require user attention.

Yes, it would be nice to have some sort of mechanism to clean stuck actions in general, ad-hoc, if needed.  But that's out of scope of the bug that was fixed here.  I can follow up with an ER.

**Comment by jillguyonnet** [comment]
Thanks for the followup!

> that is not clear in the API doc 

I agree, and I don't see an explicit mention in https://www.elastic.co/docs/reference/fleet/upgrade-elastic-agent either. In addition, it looks like `POST /api/fleet/agents/actions/{actionId}/cancel` is effectively a no-op for action types other than `UPGRADE` (which might be intentional, but it seems confusing). I've created a [small issue](https://github.com/elastic/kibana/issues/245504) to address this.

> I can follow up with an ER.

Sounds good, thanks!
