### ISSUE TITLE
Elastic Agent 8.6.x standalone deployment in Kubernetes doesn't start monitoring new pods until agent restart

### ISSUE THREAD

**Issue by drenze-athene** [elastic/elastic-agent#2269]
Since upgrading to Elastic Agent v8.6.x, I've started using condition-based autodiscovery for Kubernetes pods in Elastic Agent. When pod logs rotate, they use a `copytruncate` strategy. Elastic Agent continues ingesting the logs as expected when this happens. However, when a new pod starts, Elastic Agent does not appear to start monitoring until the agent is restarted. This includes when:

  * A new deployment happens on a node for the first time (i.e., no prior instances of that deployment were running).
  * A pod restarts on the same node.
  * A pod stops on one node and a new instance starts on another node (i.e., when a pod "switches nodes").

This has been observed with Elastic Agent v8.6.0 and v8.6.1 in EKS on Kubernetes 1.22.14.

I have also tested this with `filebeat-8.6.1` deployed to my cluster using the older-style `filebeat.autodiscover.providers` hints-based autodiscovery, and it **does not** appear to exhibit the same behavior.

I reported this issue in the [forums][1] and received a response from another user who had [reported the same issue][2] in the forums about the same time I did.

Per the other user's recommendation, I downgraded Elastic Agent to v8.5.3, which appears to have resolved the issue.

To reproduce:

  * Deploy Elastic Agent Standalone 8.6.0 or 8.6.1 with a condition-based filestream input.
  * Create a new deployment with a container that matches the filestream input configuration **after** Elastic Agent is running and logging has started.

Here is a sample input configuration, taken from a pod for which this is particularly noticeable, since it generally terminates after about two hours and a new instance is scheduled to another node:

```yaml
---
inputs:
  - id: 'filestream-myapp-0d9ea285-223f-4b6a-9207-9432b0eac168'
    name: 'filestream-myapp'
    type: 'filestream'
    use_output: 'default'
    data_stream:
      namespace: 'default'
    streams:
      # mycontainer
      - id: 'logs-${kubernetes.pod.name}-${kubernetes.container.id}'
        condition: '${kubernetes.container.name} == "mycontainer"'
        data_stream:
          dataset: 'myapp.log'
          type: 'logs'
        parsers:
          - container:
              stream: 'all'
              format: 'auto'
          - ndjson:
              expand_keys: true
              ignore_decoding_error: true
              overwrite_keys: true
              target: ''
        paths: ['/var/log/containers/*${kubernetes.container.id}.log']
        pipeline: 'logs-myapp.log'
        processors:
          - add_locale:
              format: 'offset'
        prospector.scanner.symlinks: true
        tags: ['myapp']
```

I do **not** currently have `providers.kubernetes.hints.enabled: true` set (the documentation for conditions-based autodiscovery does not require it), but I have tested it both ways with the same result.

[1]:https://discuss.elastic.co/t/elastic-agent-conditions-based-autodiscover-doesnt-pick-up-newly-scheduled-pods-containers
[2]:https://discuss.elastic.co/t/elastic-agent-autodiscovery-for-kubernetes-pod-logs-not-working-after-upgrading-to-8-6-x

**Comment by cmacknz** [comment]
Thanks for the detailed bug report. That a downgrade corrects this highly suggests this is a regression in the agent.

@elastic/obs-cloud-monitoring do you have any initial ideas on what the problem might be here?

**Comment by drenze-athene** [comment]
I'll keep an eye on it over the next few days and update if anything suggests that it is not, in fact, resolved.

**Comment by drenze-athene** [comment]
Validated this morning that this specific application spun up a new instance on a different node and it continued to ingest logs as expected.

**Comment by cmacknz** [comment]
Thanks for confirming things are fine in 8.5.3. We'll investigate what has gone wrong in 8.6.x here.

**Comment by saginadir** [comment]
@cmacknz any news about this? We had a petabyte of logs missing after we upgraded to 8.6.x

**Comment by zmoog** [comment]
This is something @elastic/obs-cloudnative-monitoring can help with.

**Comment by MichaelKatsoulis** [comment]
@drenze-athene 

I tried to reproduce your issue.
I have deployed standalone elastic agent 8.6.1 version in EKS with Kubernetes 1.24.

The configuration of agent is rather simple:
```
 inputs:
      - name: container-log
        id: container-log-${kubernetes.pod.name}-${kubernetes.container.id}
        type: filestream
        use_output: default
        meta:
          package:
            name: kubernetes
            version: 1.9.0
        data_stream:
          namespace: default
        streams:
          - data_stream:
              dataset: kubernetes.container_logs
              type: logs
            condition: '${kubernetes.container.name} == "redis"'
            prospector.scanner.symlinks: true
            parsers:
              - container: ~
            paths:
              - /var/log/containers/*${kubernetes.container.id}.log
      - name: container-log-2
        id: container-log-${kubernetes.pod.name}-${kubernetes.container.id}
        type: filestream
        use_output: default
        meta:
          package:
            name: kubernetes
            version: 1.9.0
        data_stream:
          namespace: default
        streams:
          - data_stream:
              dataset: kubernetes.container_logs
              type: logs
            condition: '${kubernetes.container.name} == "redis2"'
            prospector.scanner.symlinks: true
            parsers:
              - container: ~
            paths:
              - /var/log/containers/*${kubernetes.container.id}.log
```

I enabled two filestream inputs. First one to collect logs from container.name redis and the second from redis2.
I used a Redis [sample](https://kubernetes.io/docs/tutorials/configuration/configure-redis-using-configmap/#real-world-example-configuring-redis-using-a-configmap) example.

I killed and restarted redis pod many times, also assigned it to a different k8s node. Agent was collecting the logs every time.
Also I deployed another redis2 container and immediately agent started collecting the logs (matched by second condition).

Do you do something differently? Also share with us your full agent configuration.

Regarding this bullet:
`A new deployment happens on a node for the first time (i.e., no prior instances of that deployment were running).`

You mean that you have an input with a condition to match this container name created by that new deployment ?

**Comment by drenze-athene** [comment]
> Regarding this bullet: `A new deployment happens on a node for the first time (i.e., no prior instances of that deployment were running).`
> 
> You mean that you have an input with a condition to match this container name created by that new deployment ?

Yes.

> Do you do something differently? Also share with us your full agent configuration.

Including all inputs, my full agent configuration is rather large, with multiple inputs loaded from the `inputs.d/` subdirectory. The identical config works with 8.5.3, does not with 8.6.x. See below for a sample.

`inputs.d/myapp.yml`:

```yaml
---
inputs:
  - id: 'filestream-myapp-0d9ea285-223f-4b6a-9207-9432b0eac168'
    name: 'filestream-myapp'
    type: 'filestream'
    use_output: 'default'
    data_stream:
      namespace: 'default'
    streams:
      # mycontainer
      - id: 'logs-${kubernetes.pod.name}-${kubernetes.container.id}'
        condition: '${kubernetes.container.name} == "mycontainer"'
        data_stream:
          dataset: 'myapp.log'
          type: 'logs'
        parsers:
          - container:
              stream: 'all'
              format: 'auto'
          - ndjson:
              expand_keys: true
              ignore_decoding_error: true
              overwrite_keys: true
              target: ''
        paths: ['/var/log/containers/*${kubernetes.container.id}.log']
        pipeline: 'logs-myapp.log'
        processors:
          - add_locale:
              format: 'offset'
        prospector.scanner.symlinks: true
        tags: ['myapp']
```

`elastic-agent.yml`:

```yaml
---
id: 'elastic-agent-standalone-063fb488-772c-4963-bd79-50f5e6aa66a2'
agent:
  download:
    source_uri: 'https://artifacts.elastic.co/downloads/'
  logging:
    level: '${ELASTIC_AGENT_LOG_LEVEL}'
  monitoring:
    namespace: 'default'
    use_output: 'default'
    enabled: ${ELASTIC_AGENT_MONITORING_ENABLED}
    logs: ${ELASTIC_AGENT_MONITORING_LOGS_ENABLED}
    metrics: ${ELASTIC_AGENT_MONITORING_METRICS_ENABLED}

outputs:
  default:
    type: 'elasticsearch'
    hosts:
      - '${ES_HOST}'
    username: '${ES_USERNAME}'
    password: '${ES_PASSWORD}'
    bulk_max_size: 1024
    worker: 3

providers:
  docker.enabled: false
  # kubernetes.hints.enabled: true
```

**Comment by WoodyWoodsta** [comment]
Chiming in here to say I have what I believe is to be the same issue.

My fleet-managed agents are configured with the `kubernetes` integration:

```yaml
  - id: filestream-container-logs-d0f48059-c8eb-4bbd-81f5-2efb2aab1934
    name: kubernetes-1
    revision: 29
    type: filestream
    use_output: default
    meta:
      package:
        name: kubernetes
        version: 1.31.2
    data_stream:
      namespace: logging
    package_policy_id: d0f48059-c8eb-4bbd-81f5-2efb2aab1934
    streams:
      - id: >-
          kubernetes-container-logs-${kubernetes.pod.name}-${kubernetes.container.id}
        data_stream:
          dataset: kubernetes.container_logs
          type: logs
        prospector.scanner.symlinks: true
        paths:
          - '/var/log/containers/*${kubernetes.container.id}.log'
        parsers:
          - container:
              stream: all
              format: auto
          - ndjson:
              ignore_decoding_error: true
              target: ''
```

The behaviour I'm experiencing is approximately the same as above.

1. Logs stop for certain pods randomly (as far as I can tell)
2. Restarting pods does not resolve
3. Restarting the Agents (and by that I mean fully removing and re-adding the Agent `Daemonset` resource) will _sometimes_ fix the issue however:
	1. Over the course of 4 days of having 8.6.x installed, only ~18 of my ~80 pods cluster-wide appear in the container_logs datastream
	2. Restarting the agents will only start logs for a handful of extra pods, and at the same time, some pods' logs stop.

I'm still working on finding the exact pattern/behaviour. To me it appears fairly random (as unhelpful as that is!)

Details:
1. Fleet-managed
2. ES 8.6.1
3. k8s bare-metal, kubeadm, 2 nodes, v1.26.1

**Comment by cfuntis** [comment]
we see the same issue with "Elastic Agent on Kubernetes managed by Fleet" and the custom logs integration, solution at the moment: downgrade to 8.5.3

**Comment by michalpristas** [comment]
@drenze-athene was deployment/agent with issue managed by fleet or not?

**Comment by drenze-athene** [comment]
> @drenze-athene was deployment/agent with issue managed by fleet or not?

No. Unlike @WoodyWoodsta  and @cfuntis, mine was standalone.

**Comment by DavidConnack** [comment]
We are seeing similar behavior with a fleet hosted in elastic.co.
Ours is using the default kubernetes  intergration.
Solution was to downgrade the agents to 8.5.3

**Comment by michalpristas** [comment]
i'm trying to reproduce the issue for 2 days now with no luck. 
if anybody running into this on some managed environment could switch logs to debug and request diagnostics using UI ti would be super helpful
<img width="327" alt="image" src="https://user-images.githubusercontent.com/1522652/222149208-da3fbf21-b6d4-4f30-bb79-70af638d82f1.png">

**Comment by drenze-athene** [comment]
@WoodyWoodsta - This a good point, however I was observing this as well on new nodes which had never previously had 8.5.x deployed, since they spun up after the cutover.

**Comment by drenze-athene** [comment]
> i'm trying to reproduce the issue for 2 days now with no luck. if anybody running into this on some managed environment could switch logs to debug and request diagnostics using UI ti would be super helpful <img alt="image" width="327" src="https://user-images.githubusercontent.com/1522652/222149208-da3fbf21-b6d4-4f30-bb79-70af638d82f1.png">

I'll see what I can do. I don't use managed, but I may be able to shell into one of my pods and pull a diagnostics bundle manually. However, I don't have a sandbox environment, so I will need to upgrade one of my clusters to 8.6.2 to do this, then downgrade it again to 8.5.3, so I'll need to figure out when I can do this.

**Comment by WoodyWoodsta** [comment]
@drenze-athene Good to know!

I could grab diagnostics from my cluster (@michalpristas why are you asking for someone in a managed environment, specifically, to provide a dump?) but it might take some time to go through and redact sensitive information, as I also do not have a sandbox environment.

**Comment by michalpristas** [comment]
i think i have repro steps now.
