### ISSUE TITLE
[Agent Upgrade]: Linux agent fails on upgrade from 7.16.3>8.1.2 Snapshot and goes Unhealthy.

### ISSUE THREAD

**Issue by samratbhadra-qasource** [elastic/elastic-agent#275]
**Describe the bug:**
Agent upgrade fails and goes Unhealthy from 7.16.3>8.1.2 Snapshot.

**Build Details:**
VERSION: 8.1.2-SNAPSHOT
COMMIT: 7dce1a1c7cf6aba8782d0af02fc2d95edb5be999
BUILD: 50688
ARTIFACT LINK OF 7.16.3: https://www.elastic.co/downloads/past-releases/elastic-agent-7-16-3

**Preconditions:**
1. Elastic 8.1.2-SNAPSHOT environment should be deployed.

**Steps to Reproduce:**
1. Login to Kibana environment.
2. Navigate to Fleet Tab.
3. Upgrade lower version agents from the Agents tab.
4. Observe that agent upgrade fails and goes Unhealthy while upgrading from 7.16.3>8.1.2 Snapshot.

**Actual Result:**
Agent upgrade fails and goes Unhealthy from 7.16.3>8.1.2 Snapshot.

**Expected Result:**
Agent should be upgraded to latest version from 7.16.3>8.1.2 Snapshot.

**What's Working:**

Agent is successfully upgraded from 7.16.3>8.1.2-Snapshot without Endpoint Security Integration.
![Screenshot (287)](https://user-images.githubusercontent.com/84007952/161054604-c2bcac07-3e09-4d38-addc-48b6a68621ab.png)

**Screenshot:**

![Screenshot (285)](https://user-images.githubusercontent.com/84007952/161054652-8a09e324-5906-466d-9589-426da8131757.png)
![Screenshot (284)](https://user-images.githubusercontent.com/84007952/161054668-8a1ec9ce-5f54-4d95-a947-eecf1e6f396d.png)

**Comment by joshdover** [comment]
Also getting this on my mac as well with similar error message:

```
[elastic_agent][error] failed to dispatch actions, error: failed verification of agent binary: 2 errors occurred:
	* fetching asc file from '/Library/Elastic/Agent/data/elastic-agent-7f30bb/downloads/elastic-agent-8.1.2-darwin-x86_64.tar.gz.asc': open /Library/Elastic/Agent/data/elastic-agent-7f30bb/downloads/elastic-agent-8.1.2-darwin-x86_64.tar.gz.asc: no such file or directory
	* open /Library/Elastic/Agent/data/elastic-agent-7f30bb/downloads/elastic-agent-8.1.2-darwin-x86_64.tar.gz.sha512: no such file or directory
```

**Comment by ph** [comment]
@joshdover can you do a ls -l /Library/Elastic/Agent/data/elastic-agent-7f30bb/downloads/ ?

**Comment by ph** [comment]
@joshdover Can you send me a diagnostic of one of the problematic host?

**Comment by joshdover** [comment]
@ph below is the downloads directory and I sent you the diagnostic over DM.

```
sudo ls -l /Library/Elastic/Agent/data/elastic-agent-7f30bb/downloads/
total 412480
-rw-r--r--  1 root  wheel  32333273 Mar 23 14:49 apm-server-8.1.1-darwin-x86_64.tar.gz
-rw-r--r--  1 root  wheel       488 Mar 23 14:49 apm-server-8.1.1-darwin-x86_64.tar.gz.asc
-rw-r--r--  1 root  wheel       168 Mar 23 14:49 apm-server-8.1.1-darwin-x86_64.tar.gz.sha512
-rw-r--r--  1 root  wheel  41477489 Mar 23 14:49 endpoint-security-8.1.1-darwin-x86_64.tar.gz
-rw-r--r--  1 root  wheel       488 Mar 23 14:49 endpoint-security-8.1.1-darwin-x86_64.tar.gz.asc
-rw-r--r--  1 root  wheel       175 Mar 23 14:49 endpoint-security-8.1.1-darwin-x86_64.tar.gz.sha512
-rw-r--r--  1 root  wheel  30800476 Mar 23 14:49 filebeat-8.1.1-darwin-x86_64.tar.gz
-rw-r--r--  1 root  wheel       488 Mar 23 14:49 filebeat-8.1.1-darwin-x86_64.tar.gz.asc
-rw-r--r--  1 root  wheel       166 Mar 23 14:49 filebeat-8.1.1-darwin-x86_64.tar.gz.sha512
-rw-r--r--  1 root  wheel   8186973 Mar 23 14:49 fleet-server-8.1.1-darwin-x86_64.tar.gz
-rw-r--r--  1 root  wheel       488 Mar 23 14:49 fleet-server-8.1.1-darwin-x86_64.tar.gz.asc
-rw-r--r--  1 root  wheel       170 Mar 23 14:49 fleet-server-8.1.1-darwin-x86_64.tar.gz.sha512
-rw-r--r--  1 root  wheel  24269481 Mar 23 14:49 heartbeat-8.1.1-darwin-x86_64.tar.gz
-rw-r--r--  1 root  wheel       488 Mar 23 14:49 heartbeat-8.1.1-darwin-x86_64.tar.gz.asc
-rw-r--r--  1 root  wheel       167 Mar 23 14:49 heartbeat-8.1.1-darwin-x86_64.tar.gz.sha512
-rw-r--r--  1 root  wheel  36101125 Mar 23 14:49 metricbeat-8.1.1-darwin-x86_64.tar.gz
-rw-r--r--  1 root  wheel       488 Mar 23 14:49 metricbeat-8.1.1-darwin-x86_64.tar.gz.asc
-rw-r--r--  1 root  wheel       168 Mar 23 14:49 metricbeat-8.1.1-darwin-x86_64.tar.gz.sha512
-rw-r--r--  1 root  wheel  37950282 Mar 23 14:49 osquerybeat-8.1.1-darwin-x86_64.tar.gz
-rw-r--r--  1 root  wheel       488 Mar 23 14:49 osquerybeat-8.1.1-darwin-x86_64.tar.gz.asc
-rw-r--r--  1 root  wheel       169 Mar 23 14:49 osquerybeat-8.1.1-darwin-x86_64.tar.gz.sha512
```

**Comment by jlind23** [comment]
@pjbertels do you also have endpoint integration enable?

**Comment by michel-laterman** [comment]
I have not been able to recreate this so far, I've tried an `8.1.2-SNAPSHOT` cluster, with a policy that just has the system integration and a policy that has system+endpoint.

**Comment by redundancydisorder** [comment]
I am seeing this same issue
`[elastic_agent][error] failed to dispatch actions, error: failed verification of agent binary: 2 errors occurred:
	* fetching asc file from '/opt/Elastic/Agent/data/elastic-agent-7f30bb/downloads/elastic-agent-8.1.2-linux-x86_64.tar.gz.asc': open /opt/Elastic/Agent/data/elastic-agent-7f30bb/downloads/elastic-agent-8.1.2-linux-x86_64.tar.gz.asc: no such file or directory
	* open /opt/Elastic/Agent/data/elastic-agent-7f30bb/downloads/elastic-agent-8.1.2-linux-x86_64.tar.gz.sha512: no such file or directory`

Agent goes unhealth then back to healthy but not upgraded 

manual download of agent on client
`curl -L -O https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.1.2-linux-x86_64.tar.gz`
works without issue so connectivity to internet and elastic.co is not an issue.

**Comment by michel-laterman** [comment]
@redundancydisorder, what integrations/os' are you running on?

**Comment by redundancydisorder** [comment]
All agents that fail are running Ubuntu 18.04 or 20.04. The example from above that failed was just running the system integration. A couple agents are running Custom Logs. 

Cluster and kibana were installed at 8.1.1 and just updated to 8.12. Agents can be added with 8.1.2 with no issues.

**Comment by samoz83** [comment]
We're getting the same as @redundancydisorder with agents running on Rocky 8.4/8.5. With a range of different integrations, but all have at least system and auditd integrations.

**Comment by WiegerElastic** [comment]
I am having the same issue with my deployment. I spun up a new deployment last night on Elastic Cloud, on version 8.1.1. Added the agents (2 VPSes, running Ubuntu server 20.04 LTS). Upgraded the stack to 8.1.2. Then wanted to proceed in upgrading the machines to Agent 8.1.2. Same error on both devices.

12:59:03.830
elastic_agent
[elastic_agent][info] 2022-04-05T12:59:03+02:00 - message: Application: [a4d493a5-db03-4cda-af1a-9d76ed258667]: State changed to UPDATING: Update to version '8.1.2' started - type: 'STATE' - sub_type: 'UPDATING'
12:59:18.151
elastic_agent
[elastic_agent][error] 2022-04-05T12:59:18+02:00 - message: Application: [a4d493a5-db03-4cda-af1a-9d76ed258667]: State changed to FAILED: failed verification of agent binary: 2 errors occurred:
	* fetching asc file from '/opt/Elastic/Agent/data/elastic-agent-7f30bb/downloads/elastic-agent-8.1.2-linux-x86_64.tar.gz.asc': open /opt/Elastic/Agent/data/elastic-agent-7f30bb/downloads/elastic-agent-8.1.2-linux-x86_64.tar.gz.asc: no such file or directory
	* open /opt/Elastic/Agent/data/elastic-agent-7f30bb/downloads/elastic-agent-8.1.2-linux-x86_64.tar.gz.sha512: no such file or directory

 - type: 'ERROR' - sub_type: 'FAILED'
12:59:18.152
elastic_agent
[elastic_agent][error] failed to dispatch actions, error: failed verification of agent binary: 2 errors occurred:
	* fetching asc file from '/opt/Elastic/Agent/data/elastic-agent-7f30bb/downloads/elastic-agent-8.1.2-linux-x86_64.tar.gz.asc': open /opt/Elastic/Agent/data/elastic-agent-7f30bb/downloads/elastic-agent-8.1.2-linux-x86_64.tar.gz.asc: no such file or directory
	* open /opt/Elastic/Agent/data/elastic-agent-7f30bb/downloads/elastic-agent-8.1.2-linux-x86_64.tar.gz.sha512: no such file or directory

**Comment by joshdover** [comment]
@ph Should this be listed as an 8.2 blocker (assuming the problem is still present)?

**Comment by ph** [comment]
@joshdover @jlind23 I wouldn't consider this a blocker, the upgrade is still beta (experimental?)

**Comment by redundancydisorder** [comment]
With debug log on no information is recorded between:
`State changed to UPDATING: Update to version '8.1.2' started - type: 'STATE' - sub_type: 'UPDATING'`
and
`State changed to FAILED: failed verification of agent binary: 2 errors occurred:`

At the same time the referenced directory:
`/opt/Elastic/Agent/data/elastic-agent-7f30bb/downloads/`
had zero changes to the file system on disk. It looks like this failing download or writing to disk prior to the verification failing. 

Repeated attempts to update monitoring file system changes and can't find any attempt to write a download to disk.

**Comment by michel-laterman** [comment]
Looks like the issue here was introduced as a side effect of https://github.com/elastic/beats/pull/30281

it effects `v8.1.1+`

**Comment by michel-laterman** [comment]
Changes from https://github.com/elastic/elastic-agent/pull/255/ will fix it if we need to backport to `8.1.x` if another release is planned as the download succeeded when attempting to upgrade from `8.2.0-SNAPSHOT` to `8.3.0-SNAPSHOT` (however the upgrade did not install correctly as the binary was not linked)

**Comment by ph** [comment]
@michel-laterman Can you backport the fix to the appropriate branches.

**Comment by jlind23** [comment]
@samratbhadra-qasource can you test it again with the latest snapshot from 8.1.X?

**Comment by jlind23** [comment]
@samratbhadra-qasource can you tell me what was the commit sha used on the Elastic Agent snapshot?

**Comment by jlind23** [comment]
@samratbhadra-qasource Where is this commit sha coming from: COMMIT: a05409860677938d5bbfc6c6065c85230f54848b
?

Is it a stack one? I do not see it in Beats repository.

**Comment by samratbhadra-qasource** [comment]
Hi @jlind23,
We have deployed the **8.1.3-SNAPSHOT** kibana cloud  build from https://console.qa.cld.elstc.co/home.
This COMMIT is from the above deployed build. 
**For your reference** we have provided below screenshot that we use use for capturing kibana build details.

**NOTE:** The screenshot is from the latest **8.1.3-Snapshot** build available on cloud-qa.
![Screenshot (353)](https://user-images.githubusercontent.com/84007952/163104733-f024f27b-9e73-4c59-9f55-6109348ad8ca.png)

**Comment by jlind23** [comment]
Could you please use today's snapshot, the one with the "c44c8c" SHA? The previous one was a version built last week.

**Comment by joshdover** [comment]
Since the problem was present on older versions of Agent, isn't this always going to be reproducible when trying to _upgrade from_ an affected to version even if the version that is being _upgraded to_ is fixed? @michel-laterman maybe you could confirm based on the nature of the fix.

If what I suspect is true, then it points to the very painful impact of having bugs in our upgrade code. We probably need to have better e2e test coverage in place for this feature before we can call it GA.

**Comment by jlind23** [comment]
If you are trying to upgrade from an 8.1.1 or an 8.1.2 to something else indeed it will fail.
Otherwise it should be working.

Here @samratbhadra-qasource tried to upgrade from 7.16.3 to 8.1.3 if I am not misreading.

For the e2e test coverage it is an ongoing topic with manu in the e2e testing repository.
https://github.com/elastic/e2e-testing/issues/1643

**Comment by jlind23** [comment]
@samratbhadra-qasource looking again at the screenshot provided here: https://github.com/elastic/elastic-agent/issues/275#issuecomment-1096484869

It seems to be a timeout issue and an HTTP 404, I do not think this is related to the upgrade issue we have seen.
>

**Comment by amolnater-qasource** [comment]
Hi @jlind23 
We had reported an issue on 7.15 Snapshot for this linux agent upgrade failure at https://github.com/elastic/elastic-agent/issues/148 (In case it is helpful).
We even attempted to troubleshoot doing various ways like increasing `agent.download.timeout: 300`. However issue didn't resolve.
Thanks!

**Comment by jlind23** [comment]
@amolnater-qasource and blake is currently working on this there: https://github.com/elastic/elastic-agent/issues/104

**Comment by eric-ooi** [comment]
Upgrading from 8.1.1/8.1.2 to 8.1.3 on Linux and Windows continues to fail for me.

**Comment by blakerouse** [comment]
This is definitely a timeout issue. You can see the upgrade started at 12:54:55.063 and the timeout error message is logged at 12:56:56.460. Which is roughly 1min 30secs which is the default timeout for download, in version 8.0.1. Version 8.3.0 changed this value to 10 minutes, that will help with these type of issues.

Just because Windows and Mac finished is probably just a timing issue. The linux one could be very close to finishing but that timeout is hit right at the end.

**Comment by nimarezainia** [comment]
@samratbhadra-qasource would it be possible to repeat this test between two 8.3 snapshots to confirm it's fixed? we will work on getting the fix back ported.

**Comment by samratbhadra-qasource** [comment]
Hi @nimarezainia,

We have validated this issue on  **02** latest **8.3.0-Snapshot** cloud environments and had below observations.

We have upgraded:

- 8.0.1 released agents with endpoint Security on all OSs to 8.3.0-Snapshot build.
- 8.1.3 released agents with endpoint Security  on all OSs to 8.3.0-Snapshot build.

**Agent upgrade:**
Windows: PASS
Linux: still FAILING
MAC: PASS

**Screenshot:**
![Screenshot (393)](https://user-images.githubusercontent.com/84007952/164657732-56052354-e52b-4ef0-9a82-ea21dfaa2b09.png)
![Screenshot (394)](https://user-images.githubusercontent.com/84007952/164657857-10ed4a26-1276-4609-bb03-8d953741153f.png)
![Screenshot (395)](https://user-images.githubusercontent.com/84007952/164658002-c26a8103-2107-4c6e-b191-c25a47e027b2.png)

**Build Details:**
VERSION: 8.2.0-SNAPSHOT
COMMIT:  64479235912eecd8364a7dfd4231931839c61cf9
BUILD: 52260
ARTIFACT LINK OF 8.0.1: https://www.elastic.co/downloads/past-releases/elastic-agent-8-0-1
ARTIFACT LINK OF 8.1.3: https://www.elastic.co/downloads/past-releases/elastic-agent-8-1-3

**Note:** We are closing this issue as we are tracking same issue under **[#173](https://github.com/elastic/elastic-agent/issues/173)**

Thanks!

**Comment by jlind23** [comment]
@mukeshelastic download timeout can be configured indeed. Moreover Blake worked on a progress reporter: https://github.com/elastic/elastic-agent/pull/308
It will give users much more insights about it.

**Comment by amolnater-qasource** [comment]
### `Bug Conversion`

-  Testcase already exists for this scenario under Fleet test suite at link:
   -  [C34211](https://elastic.testrail.io/index.php?/cases/view/34211)

Thanks
