### ISSUE TITLE
Align Filestream Configuration to all Hints templates

### ISSUE THREAD

**Issue by gizas** [elastic/elastic-agent#5686]
We need to update the prospector block confguration in hint templates

The proposed Filestream configuration should be https://github.com/elastic/integrations/pull/11212

But for eg in logs template 
```yaml
prospector:
  scanner:
    fingerprint.enabled: true
    symlinks: true
file_identity.fingerprint: ~
```

This is the referencing pipeline responsible to build the packages: https://github.com/elastic/package-storage-infra/blob/main/.buildkite/pipeline.refresh-kubernetes-templates.yml
(Way to trigger it manually [here](https://github.com/elastic/package-storage-infra/pull/169#issue-1303090936)

Where the prospector is defined: https://github.com/ChrsMark/package-storage-infra/blob/54af49b06af4f7e6423574bd0c04206e6ab5e45d/jobs/refreshk8stemplates/job.go#L488-L512

**Comment by ycombinator** [comment]
@bturquet and @gizas met with me today to explain the scope of what's involved in this change and to discuss ownership of these templates.  These templates are generated from [this generator](https://github.com/ChrsMark/package-storage-infra/tree/main/jobs/refreshk8stemplates) that is run via a Buildkite pipeline.  The generator reads k8s-appropriate integration packages as input and generates the templates.  

As such, we agreed that it made sense for the Ingest team to own the generator, the Buildkite pipeline, and the resulting templates.  Integrations teams would continue to own the integrations packages.

Chatting with @swiatekm afterwards, we considered two changes in addition to the specific work mentioned in this issue:
* [ ] Moving the generator from its current location into https://github.com/elastic/elastic-agent/tree/main/dev-tools
* [ ] Adding the template files to https://github.com/elastic/elastic-agent/blob/main/.github/CODEOWNERS with each template file being associated with the corresponding integration's team + the Elastic Agent Control Plane team.  This will raise awareness with the relevant teams whenever these files are modified via PRs and ensure the changes are good.

@bturquet @gizas @swiatekm @cmacknz @jlind23 do you have any opinions on the above plan? Once we have consensus, I'll create any additional issues and we can proceed with the specific work mentioned in this issue.

**Comment by cmacknz** [comment]
> Moving the generator from its current location into https://github.com/elastic/elastic-agent/tree/main/dev-tools

It looks like the package storage has some concept of a periodic job that iterates over all the packages built into it's CI processes. https://github.com/elastic/package-storage-infra/tree/main/jobs We could replicate that here, but I'm not sure what the benefit is. It's in a perhaps more obvious place but we have to do a bunch of work to move it over without it solving a problem that couldn't just be solved by documentation instead.

> Adding the template files to https://github.com/elastic/elastic-agent/blob/main/.github/CODEOWNERS with each template file being associated with the corresponding integration's team + the Elastic Agent Control Plane team. This will raise awareness with the relevant teams whenever these files are modified via PRs and ensure the changes are good.

This makes sense, but I expect you'll have to do a lot of chasing and following up to get approvals from the authors of all these integrations every week. They also won't all necessarily know what these are or what problems they need to look for because they've been able to ignore them until now.

If we were to make a change here, I would want to see if we can figure out how to push building+testing the hints templates directly into the package development process in https://github.com/elastic/integrations/. We could change the package spec to include an "includes hints" indicator, which causes `elastic-package build` to generate the hints as they do today but whenever a package changes. We would ideally then try to figure out a way to get them tested as part of the package CI run as well.

The only hiccup with that is we still need a way to figure out how to pull the complete set of packages that support hints into the agent repository. In an ideal world, every time a package that supports hints publishes a new version it'd open a PR just for that package here to include the hints.

This would also be a significant amount of work. If we did this much work, maybe we should spend it doing something else entirely like adding an agent command that knows how to compose policies from integrations along the lines of https://github.com/elastic/ingest-dev/issues/4432. Then we wouldn't rely on the hints being pre-packaged into the container, but we'd expect people to compose their configuration and manage the hints via a GitOps like any other configuration.

**Comment by jlind23** [comment]
Adding @jsoriano and @kpollich for awareness as the [template generator](https://github.com/ChrsMark/package-storage-infra/tree/main/jobs/refreshk8stemplates) is included in one of their repositories.

> Adding the template files to https://github.com/elastic/elastic-agent/blob/main/.github/CODEOWNERS with each template file being associated with the corresponding integration's team + the Elastic Agent Control Plane team. This will raise awareness with the relevant teams whenever these files are modified via PRs and ensure the changes are good.

This could work but I agree with Craig that it means we will end up chasing integration owners and we know this is definitely not an easy thing to do..

> We could change the package spec to include an "includes hints" indicator, which causes elastic-package build to generate the hints as they do today but whenever a package changes. We would ideally then try to figure out a way to get them tested as part of the package CI run as well.

This would definitely be ideal IMO.

> The only hiccup with that is we still need a way to figure out how to pull the complete set of packages that support hints into the agent repository. 

Package developers would have to update their manifest in order to declare this change anyway.

**Comment by gizas** [comment]
Hello all, adding some info per comment:

- `Codeowners update`: I agree with this change. @ycombinator as we discussed, the CI can open the PR and then each team to be responsible to approve each corresponding part.  I see the pain of chasing each team. Just to add  on this, the CI is triggered manually only when there is need until now and we have not needed to udpate the templates more than 2 times in the last 1+ years 
- `generate the hints as they do today but whenever a package changes` : The hints templates only support specific list of [annotations](https://www.elastic.co/guide/en/fleet/current/hints-annotations-autodiscovery.html#_optional_hints_available), meaning that the work of developers in the packages is not entirely associated with the template generation. I mean that the templates are not so coupled with the changes within the packages, it is just some general reference to each package and not needed to run every time
- `We would ideally then try to figure out a way to get them tested as part of the package CI run as well.`: Addig this ref [here](https://github.com/elastic/elastic-agent/issues/2959#issuecomment-1625389433) You can have standalone agent manifests with specific inputs that include a template. Then you can start a pod with specific annotations and make some assertions (either with inspect or either with some documents indexed in specific datastream, because each template will create specific index)
- `need a way to figure out how to pull the complete set of packages that support hints into the agent repository`: @cmacknz the list is [here](https://github.com/elastic/package-storage-infra/blob/main/jobs/refreshk8stemplates/packages.go#L17). We had created this list for the packages we believe that can "live" inside kubernetes. I mean that we have excluded packages that can not be installed as k8s apps and we dont create hints templates for them.
Alternatively, you can also get a full list of packages by using:

```bash
curl -s "https://epr.elastic.co/search?kibana.version=8.16.0" | jq '.[] | .name ' | more
"1password"
"aws"
"awsfargate"
"abnormal_security"
...
```

> @bturquet @gizas @swiatekm @cmacknz @jlind23 do you have any opinions on the above plan? Once we have consensus,...

It is aligned with what we discussed. +1 from me

**Comment by swiatekm** [comment]
Apologies if I'm not completely following along, but it's still not completely clear to me what these templates are supposed to represent. Are we promising customers that if they add the `redis` hint, and then install content for the `redis` integration in Kibana, the dashboards will populate correctly? The documentation for hints seems to imply this. If so, the hints template should definitely be a part of the integration package, at least logically, and the agent should just pull it in as part of its CI.

>  the CI is triggered manually only when there is need until now and we have not needed to udpate the templates more than 2 times in the last 1+ years

@gizas how do you know it needs to be triggered? Do you monitor all the included packages for relevant changes?

**Comment by gizas** [comment]
> but it's still not completely clear to me what these templates are supposed to represent. Are we promising customers that if they add the redis hint, and then install content for the redis integration in Kibana, the dashboards will populate correctly?

The templates handle only the collection of logs and metrics part. I mean that they confgure the inputs of elastic-agent in order to be aware how to handle specific logs and metrics and to which datastream to send them

The dashboards will only work when/if the user installs the package. The dashboards are package assets and come only as part of the package installation. Because hints is supported only in standalone elastic-agent, the package installation can be done only manually.

> how do you know it needs to be triggered? 

Actually we dont know.  We need another set of templates unlsess we find a bug on the hints side or another "feature" has been introduced in input side of elastic agent ,eg the fingerprint in our case

**Comment by ycombinator** [comment]
> for changing the ownership I don't think we need to move the code to a different repository. In its current location it is already owned by a team that is not the owner of the rest of the repository. 

Agreed.  The issue description references the generator code in a _personal_ repository and I somehow missed that this repository is just a fork of an elastic-owned repository.  That's why I was suggesting moving it but we are already good here so no move is needed.
