### ISSUE TITLE
Elastic Defend fails for version 8.19.2 on MAC26 beta.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#9554]
**Kibana version:**
```
VERSION: 8.19.2
BUILD: 85749
COMMIT: 8634f44eaffa9f009f50401a2fbba85c95739a38
Artifact Link: https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.19.2-darwin-aarch64.tar.gz
```

**HOST OS:**
MAC 26.0 beta
<img width="490" height="76" alt="Image" src="https://github.com/user-attachments/assets/c3614087-3e5e-42e3-a068-027afb5bb653" />

**Preconditions:**
1. 8.19.2 Kibana cloud environment should be available.
2. Agent policy should be available having Elastic Defend integration.

**Steps to reproduce:**
1. Navigate to Agents tab.
2. Click Add agent and install MAC agent.
3. Wait for sometime and observe Elastic Defend fails with error: `failed install endpoint service: 2025-08-25 07:52:46: info: InstallLib.cpp:166 Versions below 10.15 are not supported: exit status 157.`

**Expected behavior:**
Elastic Defend should not fail for version 8.19.2 on MAC26 beta.

**Agent Logs:**
[elastic-agent-diagnostics-2025-08-25T08-01-55Z-00.zip](https://github.com/user-attachments/files/21964712/elastic-agent-diagnostics-2025-08-25T08-01-55Z-00.zip)

**Agent JSON:**
[Amols-MacBook-Pro-agent-details.json.zip](https://github.com/user-attachments/files/21964627/Amols-MacBook-Pro-agent-details.json.zip)

**Screen Capture:**

<img width="1512" height="858" alt="Image" src="https://github.com/user-attachments/assets/ab89a1aa-ef84-4ebf-a7cc-81f084b1e943" />

<img width="848" height="233" alt="Image" src="https://github.com/user-attachments/assets/511c82fb-1444-4a37-92cb-ad087df5c25b" />

**Note:**
- Working fine on 9.1.3 BC1.

<img width="1512" height="778" alt="Image" src="https://github.com/user-attachments/assets/f85a3c91-5f6f-44d2-8840-45c1e21ed33f" />

**Related Feature:**
https://github.com/elastic/ingest-dev/issues/5876

**Comment by amolnater-qasource** [comment]
@muskangulati-qasource Please review.

**Comment by pkoutsovasilis** [comment]
@amolnater-qasource this seems more like an endpoint issue rather than an elastic-agent one, could you please tag the endpoint team to have a look first?

**Comment by muskangulati-qasource** [comment]
Secondary review is Done for this ticket!

**Comment by amolnater-qasource** [comment]
Hi Team,
In further testing we have observed this issue reproducible on 9.0.5 too.

**Screen Capture:**

<img width="1512" height="778" alt="Image" src="https://github.com/user-attachments/assets/6abddd4e-3f2a-4cd9-a17f-a3e9530a9387" />

Please let us know if anything else is required from our end.
Thanks!!

**Comment by amolnater-qasource** [comment]
FYI @dasansol92

**Comment by ebeahan** [comment]
Agree with @pkoutsovasilis - will need the Endpoint team to investigate further. Reaching out to raise awareness and where to move the issue.

cc @nfritts

**Comment by nfritts** [comment]
The version.txt form the agent diagnostics indicates that the build time is `2025-08-08T15:10:55Z`.  I think this PR merged Aug 20 should have resolved it: https://github.com/elastic/endpoint-dev/pull/17004

**Comment by amolnater-qasource** [comment]
Hi Team,
We have revalidated this issue with latest released 8.18.6, 8.19.3 and 9.0.6, and found it **fixed now** for 8.18.6 and 8.19.3.

**Observations:**
- Elastic Defend gets Healthy for MAC26 on versions 8.18.6 and 8.19.3.
- On 9.0.6, Elastic Defend fails with same error.

**Artifact Links:**
https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.18.6-darwin-aarch64.tar.gz
https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.19.3-darwin-aarch64.tar.gz
https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-9.0.6-darwin-aarch64.tar.gz
**9.0.6:**
<img width="819" height="78" alt="Image" src="https://github.com/user-attachments/assets/d1fa2732-3783-44ae-a779-3f066874dabc" />

**Screen Capture:**

https://github.com/user-attachments/assets/deef04a0-369f-4a6a-8720-ae01ef2be74b

https://github.com/user-attachments/assets/76845426-dd07-46e7-8192-941bc0815731


**9.0.6:**

https://github.com/user-attachments/assets/f03711f8-064c-4b68-af07-7d22f58d93dd


Please let us know if anything else is required from our end.

Thanks!!

**Comment by ebeahan** [comment]
@amolnater-qasource can you provide a new diag for the failing 9.0.6 agent?

The [9.0 backpor](https://github.com/elastic/endpoint-dev/pull/17008)t was merged more recently. Maybe why we're seeing the issue persist @nfritts @ricardo-estc ?

**Comment by amolnater-qasource** [comment]
Hi @ebeahan 
Please find attached the latest diagnostics for 9.0.6 agent:

[elastic-agent-diagnostics-2025-09-04T07-14-04Z-00.zip](https://github.com/user-attachments/files/22133053/elastic-agent-diagnostics-2025-09-04T07-14-04Z-00.zip)
[Amols-MacBook-Pro-agent-details (1).json.zip](https://github.com/user-attachments/files/22133052/Amols-MacBook-Pro-agent-details.1.json.zip)

**Screen Capture:**
<img width="819" height="283" alt="Image" src="https://github.com/user-attachments/assets/9bc7f94a-adaa-4864-9d64-1093bebb60e5" />

Please let us know if anything else is required from our end.

Thanks!!

**Comment by ricardo-estc** [comment]
@ebeahan @amolnater-qasource backport was merged after 9.0.6 FF due to some technical errors in the backport utility. 
It should make it to 9.0.7 which is currently scheduled for September 11th - BC1

**Comment by amolnater-qasource** [comment]
Hi Team,
We have revalidated this issue with latest 9.0.7 BC1 Kibana cloud environment and found it **fixed now**.

**Observations:**
- Elastic Defend gets Healthy for MAC26 on version 9.0.7

**Artifact Links:**
https://staging.elastic.co/9.0.7-4b8eff6d/downloads/beats/elastic-agent/elastic-agent-9.0.7-darwin-aarch64.tar.gz

**Build details:**
VERSION: 9.0.7 BC1
BUILD: 85352
COMMIT: 9d44cc2d50d27f4d3ae7b72f0fe6b612508674bb

**Screen Capture:**

https://github.com/user-attachments/assets/027028e3-d498-43c3-9f0b-72a0e8b22b41

**Agent JSON:**

[Amols-MacBook-Pro-agent-details.json.zip](https://github.com/user-attachments/files/22296389/Amols-MacBook-Pro-agent-details.json.zip)


Hence, we are closing and marking this issue as **QA:Validated**.

Thanks!!

**Comment by ebeahan** [comment]
Thanks @amolnater-qasource !
